### ISSUE TITLE
Show Multiple submissions of form in one pdf

### ISSUE THREAD

**Issue by noman115pk** [UN-FAO/fast-export#4]
Hi,
It is a great library to export the formio components in to pdf, html and xlxs formats. I wanted to ask if is there any way we can print multiple submissions of form in a single pdf file separated by modified and owner of forms? I know we can loop through the submissions and create individual files but what about concatenating those individual file and generating one file?

Thanks,

**Comment by multinerd** [comment]
I've looked through the source and i don't think that's currently possible. It seems to handle 1 submission at a time.

**Comment by cabrerabywaters-zz** [comment]
Hi @noman115pk, as @multinerd says, it is not possible at the time as the export handles just 1 submission at the time.
It could be possible to modify the library and concatenate multiple html before generating the final pdf or if you want to use it as is...just generate the individual pdf and join them.
How would you imagine the API for that kind of separation that you want to achieve? 
Here an idea...
let options = {
  component: component,
// DATA COULD BE AN ARRAY OF SUBMISSIONS ?
  data: data,
// SOME KIND OF GROUP BY QUERY ???
query: {
groupBy: ['modified', 'owner' ]
},
  formio: {
    // component specific configuration
  },
  config: {
    // pdf export configuration
  }
};

FormioExport.toPdf(options).then((pdf) => {
  // do something
})

**Comment by noman115pk** [comment]
Hi @cabrerabywaters and @multinerd,
Thanks for the responses. Unfortunately i wasn't able to follow up with this thread. I modified the code and provide the list of data submissions to fast-export to provide one pdf by concatenating generated HTMLs. I modified like this in fast-export.

`_.each(this.data, (value, key) => {
    if (FormioExportUtils.isFormioSubmission(value)) {
        this.options.submission = {
            id: value._id,
            owner: value.owner,
            modified: value.modified
          };
        }
        this.structure.push(FormioComponent.create(component || this.component, value.data, this.options));
      });`

and on client side i called it as 

`submissions.push({
                    data: dataUser,
                    modified: dateUser,
                    owner: name,
                    _id: _id
                });`
